package io.github.gabriel0liv.cpmconverter.validator;

import com.fasterxml.jackson.databind.JsonNode;
import io.github.gabriel0liv.cpmconverter.diagnostics.*;
import java.util.*;

/** Materializes the persisted static project exactly once. */
final class CpmPersistedProjectParser {
  private static final Set<String> ROOTS=Set.of("head","body","left_arm","right_arm","left_leg","right_leg");
  private static final Set<String> ELEMENT_FIELDS=Set.of("name","show","texture","textureSize","offset","pos","rotation","rscale","scale","u","v","color","mirror","mcScale","glow","recolor","hidden","singleTex","extrude","locked","nameColor","faceUV","children","storeID");
  Result<CpmPersistedProjectV1> parse(JsonNode config, CpmValidatedConfigV1 validated, CpmPngMetadata png, boolean texturePresent, CpmArtifactLimits limits){
    var bag=new DiagnosticBag(); if(config==null||!config.isObject()) return Result.failure(error(DiagnosticCodes.CPM_CONFIG_INVALID,"/","config must be object")); JsonNode rootsNode=config.get("elements"); if(rootsNode==null||!rootsNode.isArray()) return Result.failure(error(DiagnosticCodes.CPM_CONFIG_INVALID,"/elements","elements must be array"));
    var roots=new ArrayList<CpmPersistedRootV1>(); var flat=new ArrayList<CpmPersistedElementV1>(); var ids=new LinkedHashMap<Long,CpmPersistedElementV1>(); var targets=new LinkedHashMap<Long,CpmPersistedTargetV1>(); var rootSeen=new HashSet<String>(); int[] next={0};
    for(int r=0;r<rootsNode.size();r++){JsonNode root=rootsNode.get(r);String p="/elements/"+r;if(!root.isObject()){bag=bag.add(error(DiagnosticCodes.CPM_INVALID_ROOT,p,"root must be object"));continue;}String id=text(root,"id",p+"/id",bag);if(id==null||!ROOTS.contains(id)||!rootSeen.add(id)){bag=bag.add(error(DiagnosticCodes.CPM_INVALID_ROOT,p+"/id","invalid or duplicate root id"));continue;} var children=new ArrayList<CpmPersistedElementV1>();JsonNode cn=root.get("children");if(cn!=null&&!cn.isArray()){bag=bag.add(error(DiagnosticCodes.CPM_INVALID_ROOT,p+"/children","children must be array"));}else if(cn!=null) for(int i=0;i<cn.size();i++) {var e=parseElement(cn.get(i),p+"/children/"+i,0,next,flat,ids,limits,bag);if(e!=null)children.add(e);} CpmPersistedRootV1 rr=new CpmPersistedRootV1(id,rootId(id),bool(root,"show",false),bool(root,"showInEditor",true),bool(root,"locked",false),vec(root.get("pos"),p+"/pos",new CpmPersistedVec3(0,0,0),bag),vec(root.get("rotation"),p+"/rotation",new CpmPersistedVec3(0,0,0),bag),bool(root,"dup",false),bool(root,"disableVanillaAnim",false),textOr(root,"name",""),intOr(root,"nameColor",0,p+"/nameColor",bag),children,p);roots.add(rr);long rid=rootId(id);if(!targets.containsKey(rid))targets.put(rid,new CpmPersistedRootTargetV1(rr));}
    if(bag.hasErrors()) return Result.failure(bag);for(var e:flat){if(e.storeId()<=6||e.storeId()>9_007_199_254_740_991L||targets.containsKey(e.storeId())){bag=bag.add(error(DiagnosticCodes.CPM_INVALID_STORE_ID,e.pointer()+"/storeID","invalid or colliding storeID"));continue;}ids.put(e.storeId(),e);targets.put(e.storeId(),new CpmPersistedElementTargetV1(e));}if(bag.hasErrors())return Result.failure(bag);
    CpmPersistedTextureV1 texture=texturePresent&&png!=null?new CpmPersistedTextureV1("skin.png",validated.skinSize(),validated.customGridSize(),png):null;return Result.success(new CpmPersistedProjectV1(1,validated.skinType(),validated.skinSize(),roots,flat,ids,targets,texture),bag);
  }
  private CpmPersistedElementV1 parseElement(JsonNode n,String p,int depth,int[] next,List<CpmPersistedElementV1> flat,Map<Long,CpmPersistedElementV1> ids,CpmArtifactLimits limits,DiagnosticBag bag){if(!n.isObject())return null;if(flat.size()>=limits.maxElements()){return null;}if(depth>limits.maxElementDepth()){return null;}for(var it=n.fieldNames();it.hasNext();) {String f=it.next();if(!ELEMENT_FIELDS.contains(f)){} }String name=textOr(n,"name","");long id=longRequired(n,"storeID",p+"/storeID",bag);if(id<=6||id>9_007_199_254_740_991L)bag.add(error(DiagnosticCodes.CPM_INVALID_STORE_ID,p+"/storeID","invalid storeID"));var children=new ArrayList<CpmPersistedElementV1>();JsonNode cn=n.get("children");if(cn!=null&&cn.isArray())for(int i=0;i<cn.size();i++){var c=parseElement(cn.get(i),p+"/children/"+i,depth+1,next,flat,ids,limits,bag);if(c!=null)children.add(c);}CpmPersistedUvV1 uv=parseUv(n,p,bag);var e=new CpmPersistedElementV1(name,bool(n,"show",false),bool(n,"texture",false),intOr(n,"textureSize",1,p+"/textureSize",bag),vec(n.get("offset"),p+"/offset",new CpmPersistedVec3(0,0,0),bag),vec(n.get("pos"),p+"/pos",new CpmPersistedVec3(0,0,0),bag),vec(n.get("rotation"),p+"/rotation",new CpmPersistedVec3(0,0,0),bag),vec(n.get("size"),p+"/size",new CpmPersistedVec3(0,0,0),bag),vec(n.get("rscale"),p+"/rscale",new CpmPersistedVec3(1,1,1),bag),vec(n.get("scale"),p+"/scale",new CpmPersistedVec3(1,1,1),bag),uv,n.has("color")?textOr(n,"color",""):"000000",bool(n,"mirror",false),doubleOr(n,"mcScale",1,p+"/mcScale",bag),bool(n,"glow",false),bool(n,"recolor",false),bool(n,"hidden",false),bool(n,"singleTex",false),bool(n,"extrude",false),bool(n,"locked",false),intOr(n,"nameColor",0,p+"/nameColor",bag),id,children,next[0]++,depth,p);flat.add(e);return e;}
  private CpmPersistedUvV1 parseUv(JsonNode n,String p,DiagnosticBag bag){if(!n.has("faceUV")){int u=intOr(n,"u",0,p+"/u",bag),v=intOr(n,"v",0,p+"/v",bag);return new CpmPersistedBoxUvV1(u,v);}JsonNode f=n.get("faceUV");if(!f.isObject()||f.isEmpty()){bag.add(error(DiagnosticCodes.UV_INVALID,p+"/faceUV","faceUV must be non-empty object"));return null;}var map=new LinkedHashMap<CpmPersistedFace,CpmPersistedFaceUvV1>();for(var it=f.fields();it.hasNext();){var x=it.next();try{var face=CpmPersistedFace.valueOf(x.getKey().toUpperCase(Locale.ROOT));JsonNode q=x.getValue();int sx=intOr(q,"sx",0,p+"/faceUV/"+x.getKey()+"/sx",bag),sy=intOr(q,"sy",0,p+"/faceUV/"+x.getKey()+"/sy",bag),ex=intOr(q,"ex",0,p+"/faceUV/"+x.getKey()+"/ex",bag),ey=intOr(q,"ey",0,p+"/faceUV/"+x.getKey()+"/ey",bag);String rot=textOr(q,"rot","0");map.put(face,new CpmPersistedFaceUvV1(sx,sy,ex,ey,switch(rot){case "90"->CpmPersistedUvRotation.ROT_90;case "180"->CpmPersistedUvRotation.ROT_180;case "270"->CpmPersistedUvRotation.ROT_270;default->CpmPersistedUvRotation.ROT_0;},bool(q,"autoUV",false)));}catch(IllegalArgumentException ex){bag.add(error(DiagnosticCodes.UV_FACE_UNKNOWN,p+"/faceUV/"+x.getKey(),"unknown face"));}}return new CpmPersistedPerFaceUvV1(map);}
  private static long rootId(String id){return switch(id){case "head"->0;case "body"->1;case "left_arm"->2;case "right_arm"->3;case "left_leg"->4;case "right_leg"->5;default->-1;};}
  private static String text(JsonNode n,String f,String p,DiagnosticBag b){JsonNode v=n.get(f);if(v==null||!v.isTextual()||v.textValue().isBlank()){b.add(error(DiagnosticCodes.CPM_INVALID_ROOT,p,"required string"));return null;}return v.textValue();}private static String textOr(JsonNode n,String f,String d){return n.has(f)&&n.get(f).isTextual()?n.get(f).textValue():d;}private static boolean bool(JsonNode n,String f,boolean d){return !n.has(f)||n.get(f).isBoolean()?n.path(f).asBoolean(d):d;}private static int intOr(JsonNode n,String f,int d,String p,DiagnosticBag b){if(!n.has(f))return d;JsonNode v=n.get(f);if(!v.isIntegralNumber()||!v.canConvertToInt()){b.add(error(DiagnosticCodes.CPM_CONFIG_INVALID,p,"integer required"));return d;}return v.intValue();}private static long longRequired(JsonNode n,String f,String p,DiagnosticBag b){JsonNode v=n.get(f);if(v==null||!v.isIntegralNumber()||!v.canConvertToLong()){b.add(error(DiagnosticCodes.CPM_INVALID_STORE_ID,p,"safe integer required"));return -1;}return v.longValue();}private static double doubleOr(JsonNode n,String f,double d,String p,DiagnosticBag b){if(!n.has(f))return d;JsonNode v=n.get(f);if(!v.isNumber()||!Double.isFinite(v.doubleValue())){b.add(error(DiagnosticCodes.CPM_CONFIG_INVALID,p,"finite number required"));return d;}return v.doubleValue();}private static CpmPersistedVec3 vec(JsonNode n,String p,CpmPersistedVec3 d,DiagnosticBag b){if(n==null)return d;if(!n.isObject()||!n.has("x")||!n.has("y")||!n.has("z")){b.add(error(DiagnosticCodes.CPM_CONFIG_INVALID,p,"vector x/y/z required"));return d;}try{return new CpmPersistedVec3(n.get("x").doubleValue(),n.get("y").doubleValue(),n.get("z").doubleValue());}catch(Exception e){b.add(error(DiagnosticCodes.CPM_CONFIG_INVALID,p,"finite vector required"));return d;}}
  private static Diagnostic error(String c,String p,String m){return new Diagnostic(Severity.ERROR,DiagnosticCode.fromCatalog(c),new SourceLocation(new SourcePath("config.json"),null,null,p,null),m,"repair config",null,null,new TreeMap<>());}
}
