package io.github.gabriel0liv.cpmconverter.validator;

import com.fasterxml.jackson.databind.JsonNode;
import io.github.gabriel0liv.cpmconverter.diagnostics.*;
import java.util.*;

final class CpmPersistedConfigValidator {
  private static final Set<String> TOP=Set.of("version","skinType","skinSize","textures","elements");
  Result<CpmValidatedConfigV1> validate(JsonNode root){var bag=new DiagnosticBag(); for(var it=root.fieldNames();it.hasNext();){String f=it.next();if(!TOP.contains(f))bag=bag.add(error(DiagnosticCodes.CPM_FEATURE_UNSUPPORTED,"/"+f,"unsupported config property"));} JsonNode v=root.get("version"),e=root.get("elements"); if(v==null||!v.isIntegralNumber())bag=bag.add(error(DiagnosticCodes.CPM_CONFIG_INVALID,"/version","version must be an integer")); else if(v.intValue()!=1)bag=bag.add(error(DiagnosticCodes.CPM_UNSUPPORTED_VERSION,"/version","unsupported version")); if(e==null||!e.isArray())bag=bag.add(error(DiagnosticCodes.CPM_CONFIG_INVALID,"/elements","elements must be an array")); String skin=root.path("skinType").asText("default"); if(!skin.equals("default")&&!skin.equals("slim"))bag=bag.add(error(DiagnosticCodes.CPM_CONFIG_INVALID,"/skinType","unsupported skinType")); JsonNode size=root.get("skinSize"); int sx=64,sy=64; if(size!=null){if(!size.isObject())bag=bag.add(error(DiagnosticCodes.CPM_CONFIG_INVALID,"/skinSize","skinSize must be object")); else {JsonNode x=size.get("x"),y=size.get("y"); if(x==null||!x.isIntegralNumber()||x.intValue()<=0)bag=bag.add(error(DiagnosticCodes.CPM_CONFIG_INVALID,"/skinSize/x","x must be positive integer")); else sx=x.intValue(); if(y==null||!y.isIntegralNumber()||y.intValue()<=0)bag=bag.add(error(DiagnosticCodes.CPM_CONFIG_INVALID,"/skinSize/y","y must be positive integer")); else sy=y.intValue();}} JsonNode textures=root.get("textures"); boolean custom=false,anim=false; if(textures!=null){JsonNode skinNode=textures.get("skin"); if(skinNode==null||!skinNode.isObject())bag=bag.add(error(DiagnosticCodes.CPM_CONFIG_INVALID,"/textures/skin","skin texture object required")); else {custom=skinNode.path("customGridSize").asBoolean(false); anim=skinNode.path("anim").isArray()&&!skinNode.path("anim").isEmpty(); if(skinNode.has("anim")&&!skinNode.path("anim").isArray())bag=bag.add(error(DiagnosticCodes.CPM_CONFIG_INVALID,"/textures/skin/anim","anim must be array")); if(anim)bag=bag.add(error(DiagnosticCodes.CPM_FEATURE_UNSUPPORTED,"/textures/skin/anim","animated textures unsupported"));}} if(bag.hasErrors())return Result.failure(bag); return Result.success(new CpmValidatedConfigV1(root,1,skin,new CpmPersistedSize2i(sx,sy),custom,anim),bag); }
  private static Diagnostic error(String c,String p,String m){return new Diagnostic(Severity.ERROR,DiagnosticCode.fromCatalog(c),new SourceLocation(new SourcePath("config.json"),null,null,p,null),m,"repair config.json",null,null,new TreeMap<>());}
}
